# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc7dbb38c79f19a6d44bed5218678e0a89a9ac9c177e52ace97be1c4d4d8ca104774ea60a4f0c09716bfca0e29c0d43e42d74ad23d195c67aede6c20be134f77

test:
  secret_key_base: 03baaebdd5267597469924fa65754f04a48c40413d4de5dbf6dd89f8b27292b0cf266f20c6856fd89cacaf9a376b5fbe3e6801943bdc1710dde798b1382e5703

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
